config/routes.rb
Rails.application.routes.draw do
  get "dashboard/index"
  get "dashboard/compare", as: :compare
  resources :csv_files, only: %i[index new create]
  resources :robot_reports, only: %i[index show new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  # root "robot_reports#index"
  root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/location_correlatable.rb
# frozen_string_literal: true

module LocationCorrelatable
  extend ActiveSupport::Concern

  included do
    delegate :scanned, :occupied, :detected_barcodes, to: :report_location, allow_nil: true
  end

  OUTCOME_STATUS_CATEGORY = {
    not_found: :no_data,
    not_scanned: :no_data,
    item_unidentified: :no_data,
    empty_empty: :ok,
    item_ok: :ok
  }.tap { |h| h.default = :discrepancy }.freeze

  def status
    @status ||= if report_location.nil?
      :not_found
    elsif !scanned
      :not_scanned
    elsif item.nil? && !occupied
      :empty_empty
    elsif item.nil?
      :empty_occupied
    elsif !occupied
      :item_missing
    elsif detected_barcodes.empty?
      :item_unidentified
    elsif detected_barcodes.one? && item == detected_barcodes[0]
      :item_ok
    elsif item.in?(detected_barcodes)
      :item_extra
    else
      :item_wrong
    end
  end

  def category
    @category ||= OUTCOME_STATUS_CATEGORY[status]
  end

  def decorate
    LocationCorrelatableDecorator.new(self)
  end
end

app/models/csv_file.rb
# frozen_string_literal: true

require "csv"

class CSVFile < ApplicationRecord
  has_one_attached :file, dependent: :destroy
  validates :file, presence: true, blob: {content_type: ["text/csv"]}

  attr_reader :category_count

  def name
    "#{created_at.to_date.inspect} #{file.blob.filename}"
  end

  def locations
    @locations ||= rows.map { |row| Location.new(row.to_h).decorate }
  end

  def compare_with(report)
    @category_count = Hash.new(0)
    locations.each do |location|
      location.report_location = report[location.location]
      category_count[location.category] += 1
    end
  end

  private

  def rows
    CSV.parse(file.download, headers: true, header_converters: proc { |h| h.downcase.to_sym })
  end
end

app/models/location.rb
# frozen_string_literal: true

Location = Struct.new("Location", :location, :item, :report_location, keyword_init: true) do
  include LocationCorrelatable
end

app/models/robot_report.rb
# frozen_string_literal: true

class RobotReport < ApplicationRecord
  has_one_attached :file, dependent: :destroy
  validates :file, presence: true, blob: {content_type: ["application/json"]}

  ReportLocation = Struct.new("ReportLocation", :name, :scanned, :occupied, :detected_barcodes, keyword_init: true)

  def name
    "#{created_at.to_date.inspect} #{file.blob.filename}"
  end

  def report
    @report ||= locations.index_by(&:name)
  end

  private

  def parsed_data
    JSON.parse(file.download, symbolize_names: true)
  end

  def locations
    parsed_data.map { |row| ReportLocation.new(row) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  wrap_parameters false
end

app/controllers/csv_files_controller.rb
class CSVFilesController < ApplicationController
  layout false

  # GET /csv_files
  def index
    @csv_files = CSVFile.order(id: :desc)
  end

  # GET /csv_files/new
  def new
    @csv_file = CSVFile.new
  end

  # POST /csv_files
  def create
    @csv_file = CSVFile.new(csv_file_params)

    if @csv_file.save
      @csv_files = CSVFile.order(id: :desc)
      render :index
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def csv_file_params
    params.permit(csv_file: :file)[:csv_file]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action do
    @csv_files = CSVFile.order(id: :desc)
    @robot_reports = RobotReport.order(id: :desc)
  end

  def index
  end

  def compare
    @csv_file = CSVFile.find(params[:csv_file_id])
    report = RobotReport.find(params[:robot_report_id]).report
    @csv_file.compare_with(report)
  end
end

app/controllers/robot_reports_controller.rb
class RobotReportsController < ApplicationController
  skip_before_action :verify_authenticity_token

  # GET /robot_reports or /robot_reports.json
  def index
    @robot_reports = RobotReport.all
  end

  # GET /robot_reports/1 or /robot_reports/1.json
  def show
    @robot_report = RobotReport.find(params[:id])
  end

  # GET /robot_reports/new
  def new
    @robot_report = RobotReport.new
  end

  # POST /robot_reports or /robot_reports.json
  def create
    @robot_report = if request.format.json? && !request.params.key?(:robot_report)
      RobotReport.new(file: {io: StringIO.new(request.raw_post), filename: "#{Date.today}_report.json"})
    else
      RobotReport.new(robot_report_params)
    end

    respond_to do |format|
      if @robot_report.save
        format.html { redirect_to robot_report_url(@robot_report), notice: "Robot report was successfully created." }
        format.json { render :show, status: :created, location: @robot_report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @robot_report.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def robot_report_params
    params.permit(robot_report: :file)[:robot_report]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_files_helper.rb
module CSVFilesHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
  LOCATION_REPORT_ROW_CLASS = {
    ok: "bg-green-50",
    no_data: "bg-yellow-50",
    discrepancy: "bg-red-50"
  }.freeze

  def location_report_row_class(location)
    LOCATION_REPORT_ROW_CLASS[location.category]
  end
end

app/helpers/robot_reports_helper.rb
module RobotReportsHelper
end

app/views/csv_files/_csv_file.html.erb
<div id="<%= dom_id csv_file %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= csv_file.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this CSV file", csv_file, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this CSV file", edit_csv_file_path(csv_file), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/csv_files/_form.html.erb
<%= form_with(model: csv_file, class: "contents") do |form| %>
  <% if csv_file.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(csv_file.errors.count, "error") %> prohibited this csv_file from being saved:</h2>

      <ul>
        <% csv_file.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="flex">
    <label for="csv_file_id" class="block text-m font-medium text-gray-700 mr-4">CSV file</label>
    <%= link_to "Cancel", csv_files_path, class: "text-blue-600" %>
  </div>

  <div class="flex">
    <%= form.file_field :file, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-1 mt-1", accept: ".csv" %>

    <%= form.submit "Upload CSV", class: "rounded-md ml-2 px-2 bg-blue-500 text-white  font-small cursor-pointer hover:bg-blue-600" %>
  </div>
<% end %>

app/views/csv_files/_select.html.erb
<%= turbo_frame_tag "choose_csv_file" do %>
  <div class="flex">
    <label for="csv_file_id" class="block text-m font-medium text-gray-700 mr-4">CSV file</label>
    <%= link_to "Upload new CSV file", new_csv_file_path, class: "text-blue-600" %>
  </div>

  <%= form.select :csv_file_id, options_for_select(csv_files.map { |csv_file| [csv_file.name, csv_file.id] }, params[:csv_file_id]), {}, {class: "mt-1 block w-240 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:border-blue-300"} %>

  <script type="application/javascript">
    document.getElementById("compare-button-container").setAttribute("class", "items-center space-x-4 text-center mt-3 visible");
  </script>
<% end %>

app/views/csv_files/index.html.erb
<%= form_with url: "/dashboard/compare", method: :get do |form| %>
  <%= render "csv_files/select", form:, csv_files: @csv_files %>
<% end %>

app/views/csv_files/new.html.erb
<%= turbo_frame_tag "choose_csv_file" do %>
  <%= render "form", csv_file: @csv_file %>

  <script type="application/javascript">
    document.getElementById("compare-button-container").setAttribute("class", "hidden");
  </script>
<% end %>

app/views/dashboard/_form.html.erb
<div class="container mx-auto mt-8 w-full">
  <%= form_with url: "/dashboard/compare", method: :get do |form| %>
    <div class="flex items-center space-x-4">
      <div class="w-1/2">
        <%= render "csv_files/select", form:, csv_files: @csv_files %>
      </div>

      <div class="w-1/2">
        <label for="robot_report_id" class="block text-m font-medium text-gray-700">Robot Report</label>
        <%= form.select :robot_report_id, options_for_select(@robot_reports.map { |robot_report| [robot_report.name, robot_report.id] }, params[:robot_report_id]), {}, {class: "mt-1 block w-240 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:border-blue-300"} %>
      </div>
    </div>

    <div class="items-center space-x-4 text-center mt-3" id="compare-button-container">
      <button type="submit" class="px-4 py-2 text-white bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none focus:ring focus:border-blue-300" id="compare">
        Compare
      </button>

      <% if params[:action] == "compare" %>
        <%= link_to "Download .csv", compare_path(**request.query_parameters, format: "csv"), class: "text-blue-600" %>

        <%= link_to "Download .xlsx", compare_path(**request.query_parameters, format: "xlsx"), class: "text-blue-600" %>

        <button id="copy-button" class="text-blue-600">Copy URL</button>
        <span id="current-url" class="hidden"></span>
      <% end %>
    </div>
  <% end %>
</div>

<script type="application/javascript">
  document.getElementById('current-url').innerText = window.location.href;

  document.getElementById('copy-button').addEventListener('click', function() {
    var currentUrl = document.getElementById('current-url');

    // Create a temporary input element
    var tempInput = document.createElement('input');
    document.body.appendChild(tempInput);
    tempInput.value = currentUrl.innerText;

    // Select the text in the input element
    tempInput.select();
    tempInput.setSelectionRange(0, 99999); /* For mobile devices */

    // Copy the text to the clipboard
    document.execCommand('copy');

    // Remove the temporary input element
    document.body.removeChild(tempInput);

    // Alert or provide feedback that the URL has been copied
    alert('URL copied to clipboard: ' + currentUrl.innerText);
  });
</script>

app/views/dashboard/_report.html.erb
<div class="container mx-auto mt-3">
  <table class="min-w-full divide-y divide-gray-200 my-6">
    <thead>
      <tr>
        <th class="px-6 py-4 bg-gray-50 text-center text-xs font-large text-gray-500 uppercase tracking-wider">✅ OK</th>
        <th class="px-6 py-4 bg-gray-50 text-center text-xs font-large text-gray-500 uppercase tracking-wider">🚧 Warning</th>
        <th class="px-6 py-4 bg-gray-50 text-center text-xs font-large text-gray-500 uppercase tracking-wider">🚨 Discrepancy</th>
      </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-200">
      <tr>
        <td class="px-12 py-3 whitespace-nowrap text-center bg-green-50">
          <%= csv_file.category_count[:ok] %>
          <div class="relative inline-block">
            <span class="tooltip">
              <span class="tooltip-text">The number of successfully scanned <br>locations where the CSV file <br>data matches the robot report.</span>
              <span class="circle text-white bg-blue-400 flex items-center justify-center h-4 w-4 rounded-full cursor-pointer mx-1">?</span>
            </span>
          </div>
        </td>
        <td class="px-12 py-3 whitespace-nowrap text-center bg-yellow-50">
          <%= @csv_file.category_count[:no_data] %>
          <div class="relative inline-block">
            <span class="tooltip">
              <span class="tooltip-text">The number of locations that <br>were not scanned successfully, <br>as well as those for which the <br>barcode could not be identified.</span>
              <span class="circle text-white bg-blue-400 flex items-center justify-center h-4 w-4 rounded-full cursor-pointer mx-1">?</span>
            </span>
          </div>
        </td>
        <td class="px-12 py-3 whitespace-nowrap text-center bg-red-50">
          <%= @csv_file.category_count[:discrepancy] %>
          <span class="tooltip">
            <span class="tooltip-text">The number of locations where <br>a discrepancy was observed between <br>the CSV file and the robot report <br>(e.g. missing item, wrong item, occupied <br>location should have been empty).</span>
            <span class="circle text-white bg-blue-400 flex items-center justify-center h-4 w-4 rounded-full cursor-pointer mx-1">?</span>
          </span>
        </td>
      </tr>
    </tbody>
  </table>
  <table class="min-w-full divide-y divide-gray-200">
    <thead>
      <tr>
        <th class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Location Name</th>
        <th class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Successfully Scanned</th>
        <th class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Occupied</th>
        <th class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Expected Barcodes</th>
        <th class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actual Barcodes</th>
        <th class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Outcome Status</th>
      </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-200">
      <% csv_file.locations.each do |location| %>
        <tr class="<%= location_report_row_class(location) %>">
          <td class="px-6 py-3 whitespace-nowrap"><%= location.location %></td>
          <td class="px-6 py-3 whitespace-nowrap text-center"><%= location.scanned_emoji %></td>
          <td class="px-6 py-3 whitespace-nowrap text-center"><%= location.occupied_emoji %></td>
          <td class="px-6 py-3 whitespace-nowrap"><%= location.item %></td>
          <td class="px-6 py-3 whitespace-nowrap"><%= location.detected_items %></td>
          <td class="px-6 py-3 whitespace-nowrap"><%= t("location_status.#{location.status}") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/compare.csv.erb
<%= CSV.generate_line(["✅ OK", "🚧 Warning", "🚨 Discrepancy"]) -%>
<%= CSV.generate_line(@csv_file.category_count.values_at(:ok, :no_data, :discrepancy)) -%>

<%= CSV.generate_line(["Location Name", "Successfully Scanned", "Occupied", "Expected Barcodes", "Actual Barcodes", "Outcome Status"]) -%>
<%- @csv_file.locations.each do |location| -%>
<%== CSV.generate_line(location.report_row) -%>
<%- end -%>

app/views/dashboard/compare.html.erb
<div>
  <h1 class="font-bold text-4xl">Comparison Report</h1>
</div>

<%= render "form", csv_files: @csv_files, robot_reports: @robot_reports %>
<%= render "report", csv_file: @csv_file, robot_reports: @robot_reports %>

app/views/dashboard/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Comparison Report</h1>
</div>

<%= render "form", csv_files: @csv_files, robot_reports: @robot_reports %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warehouse Review</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      .tooltip {
        position: relative;
        display: inline-block;
      }

      .tooltip-text {
        visibility: hidden;
        width: max-content;
        background-color: #1a202c;
        color: white;
        text-align: center;
        border-radius: 4px;
        padding: 0.5rem;
        position: absolute;
        z-index: 1;
        bottom: 125%;
        left: 50%;
        margin-left: -80px; /* Adjust this value based on your design */
        opacity: 0;
        transition: opacity 0.3s;
      }

      .tooltip:hover .tooltip-text {
        visibility: visible;
        opacity: 1;
      }
    </style>
  </head>
  <body>
    <main class="container mx-auto my-6">
      <%= yield %>
    </main>
  </body>
</html>

app/views/robot_reports/_form.html.erb
<%= form_with(model: robot_report, class: "contents") do |form| %>
  <% if robot_report.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(robot_report.errors.count, "error") %> prohibited this robot_report from being saved:</h2>

      <ul>
        <% robot_report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :file %>
    <%= form.file_field :file, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", accept: ".json" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/robot_reports/_robot_report.html.erb
<div id="<%= dom_id robot_report %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= robot_report.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this robot report", robot_report, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/robot_reports/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Robot reports</h1>
    <%= link_to "New robot report", new_robot_report_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="robot_reports" class="min-w-full">
    <%= render @robot_reports %>
  </div>
</div>

app/views/robot_reports/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New robot report</h1>

  <%= render "form", robot_report: @robot_report %>

  <%= link_to "Back to robot reports", robot_reports_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/robot_reports/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @robot_report %>

    <%= link_to "Back to robot_reports", robot_reports_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>